<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>NebulaAPI</AssemblyName>
    <RootNamespace>Virial</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <NoWin32Manifest>true</NoWin32Manifest>
    <PackageId>NebulaAPI</PackageId>
    <Title>Nebula API</Title>
	<LangVersion>latest</LangVersion>
    <Version>3.2.0</Version>
    <Authors>Dolly</Authors>
    <Description>Among UsのMod "Nebula on the Ship"におけるスクリプトで使用できるAPIです。</Description>
    <PackageProjectUrl>https://dolly1016.github.io/Virial.Doc/</PackageProjectUrl>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<DebugType>embedded</DebugType>
	<WarningLevel>7</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AmongUs.GameLibs.Steam" Version="2025.4.15" />
    <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" />
  </ItemGroup>
	
</Project>
